### ISSUE TITLE
Incorrect number of memory words to operand type?

### ISSUE THREAD

**Issue by dassaf1** [dassaf1/c-assembler#14]
operand type "10" (Marix) can be 2 memory words (in case of 2 registers i.e. [r1][r2]) or 3 memory words (in case of numbers i.e [2][4]) 

![image](https://user-images.githubusercontent.com/6606837/29186495-5c838bf4-7e15-11e7-9069-c368a0a5e8ba.png)

**Comment by thebestdafna** [comment]
No.
Please see table in page 19.
